# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.IntegerField(unique=True)),
                ('chat_id', models.BigIntegerField()),
                ('chat_type', models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('channel', 'Channel')], max_length=255)),
                ('chat_name', models.CharField(max_length=4096)),
                ('message_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('obsolete', models.BooleanField(default=False)),
                ('from_username', models.CharField(blank=True, max_length=32, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('original_data', models.TextField()),
            ],
        ),
    ]
